### ISSUE TITLE
Inconsistent default retries

### ISSUE THREAD

**Issue by wernight** [TomFrost/node-attempt#3]
On https://www.npmjs.com/package/attempt it shows `Default: 5. The number of times to retry`.

On https://github.com/TomFrost/node-attempt it shows `Default: 2. The number of times to retry`.

**Comment by TomFrost** [comment]
Thanks for pointing this out!  Waiting for this resolution before I can publish the fix: https://github.com/npm/npm/issues/7520

**Comment by wernight** [comment]
Diverging a bit, but isn't 2 retries meaning it may actually do the operation 3 times? In that case I'd suggest to change so that it's the total number of attempts (i.e., 3 or 6 by default).

**Comment by TomFrost** [comment]
NPM and Github are now in sync with default retries. Thanks for the wording suggestion! I've updated the README on Github with the clarification (will go to NPM with the next patch). I'm open to deprecating the 'retries' option and, instead, sending in something like `totalAttempts`, but since that would be a minor release instead of just a patch, I wanted to get the patch out now.
